#!/bin/sh

BASEDIR=$(git rev-parse --show-toplevel)
files=$(git diff --cached --name-only --diff-filter=ACM | grep '.go$')

for file in $files; do
  gofmt -l -s -w "${BASEDIR}/${file}"
  git add "${BASEDIR}/${file}"
done
